# main.py — Generated by VIA for: build a simple fullstack application for improving the iq levels by playing the games and solving the puzzles
# Deployable FastAPI backend for Render

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import os

app = FastAPI(
    title="Build A Simple Fullstack Application For",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory data store (replace with DB in production)
items_data = [
    {"id": 1, "question": "What comes next in the sequence: 2, 4, 8, 16, ?", "options": ["24", "32", "28", "20"], "answer": "32", "category": "Pattern Recognition"},
    {"id": 2, "question": "If all Bloops are Razzles and all Razzles are Lazzles, then all Bloops are definitely Lazzles?", "options": ["True", "False"], "answer": "True", "category": "Logical Reasoning"},
    {"id": 3, "question": "Which number is the odd one out: 3, 5, 11, 14, 23, 29?", "options": ["3", "5", "14", "29"], "answer": "14", "category": "Number Series"},
    {"id": 4, "question": "A clock shows 3:15. What is the angle between the hour and minute hands?", "options": ["0°", "7.5°", "15°", "22.5°"], "answer": "7.5°", "category": "Spatial Reasoning"},
    {"id": 5, "question": "Complete the analogy: Book is to Reading as Fork is to ?", "options": ["Cooking", "Eating", "Kitchen", "Food"], "answer": "Eating", "category": "Verbal Reasoning"},
    {"id": 6, "question": "What is 15% of 200?", "options": ["25", "30", "35", "40"], "answer": "30", "category": "Numerical"},
    {"id": 7, "question": "If you rearrange the letters 'CIFAIPC', you get the name of a ?", "options": ["City", "Animal", "Ocean", "Country"], "answer": "Ocean", "category": "Verbal"},
    {"id": 8, "question": "Which shape has the most sides: Pentagon, Hexagon, Octagon, Heptagon?", "options": ["Pentagon", "Hexagon", "Octagon", "Heptagon"], "answer": "Octagon", "category": "Spatial"},
    {"id": 9, "question": "5 + 3 × 2 = ?", "options": ["16", "11", "13", "10"], "answer": "11", "category": "Numerical"},
    {"id": 10, "question": "What is the next prime number after 7?", "options": ["8", "9", "10", "11"], "answer": "11", "category": "Pattern Recognition"},
]

@app.get("/")
def root():
    return {"app": "Build A Simple Fullstack Application For", "status": "running", "generated_by": "VIA"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/questions")
def get_questions():
    return items_data

@app.post("/api/v1/submit")
def submit_score(payload: dict):
    score   = payload.get("score", 0)
    total   = payload.get("total", len(items_data))
    pct     = round((score / total) * 100, 1) if total else 0
    if pct >= 90:   iq_level = "Genius (IQ 140+)"
    elif pct >= 80: iq_level = "Very Intelligent (IQ 120-139)"
    elif pct >= 70: iq_level = "Intelligent (IQ 110-119)"
    elif pct >= 60: iq_level = "Above Average (IQ 100-109)"
    else:           iq_level = "Average (IQ 90-99)"
    return {"score": score, "total": total, "percentage": pct, "iq_level": iq_level}

@app.get("/api/v1/stats")
def get_stats():
    return {"total": len(items_data), "active": len(items_data), "categories": list(set(q["category"] for q in items_data))}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
